let suggestions = [
	'Channel',
	'CodingLab',
	'CodingNepal',
	'YouTube',
	'YouTuber',
	'YouTube Channel',
	'Blogger',
	'Bollywood',
	'Vlogger',
	'Vechiles',
	'Facebook',
	'Freelancer',
	'Facebook Page',
	'Designer',
	'Developer',
	'Login Form in HTML & CSS',
	'How to learn HTML & CSS',
	'How to learn JavaScript',
	'How to become Freelancer',
	'How to become Web Designer',
	'How to start Gaming Channel',
	'How to start YouTube Channel',
	'What does HTML stands for?',
	'What does CSS stands for?',
	'web',
	'web design',
	'web designer',
	'web developer',
	'web development',
	'web programming',
	'back-end developer',
	'front-end developer',
	'full-stack developer',
	'responsive design',
	'user exprince',
	'best practice',
	'programming',
	'javascript',
	'bootstrap',
	'react.js',
	'angular',
	'node-js',
	'vue.js',
	'html',
	'css',
	'php',
]

export default suggestions
